name: Trigger Semaphore via Integration

on:
  pull_request:
    types: [closed]
    branches:
      - main   # adjust to your target branch

jobs:
  trigger-semaphore:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Semaphore Integration
        run: |
          curl -X POST \
          -H "Authorization: Token ${{ secrets.SEMAPHORE_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          http://35.181.33.202:3000/api/integrations/ncurdnw6av6yu7e5
